In [2]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv('smsspamcollection1.tsv', sep='\t')

In [7]:
df.head(5)

label                                            message  length  punct
0   ham  Go until jurong point, crazy.. Available only ...   111.0    9.0
1   ham                      Ok lar... Joking wif u oni...    29.0    6.0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...   155.0    6.0
3   ham  U dun say so early hor... U c already then say...    49.0    6.0
4   ham  Nah I don't think he goes to usf, he lives aro...    61.0    2.0

In [8]:
df.isnull().sum()

label      0
message    0
length     0
punct      0
dtype: int64

In [9]:
df.dropna(inplace=True)

In [12]:
df['label'].value_counts()

label
ham     4830
spam     753
Name: count, dtype: int64

In [13]:
######### Data Split ###########

In [15]:
X = df['message']
Y = df['label']

In [16]:
############# Data training splitting #######################

from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y, test_size=0.33, random_state=42)

In [17]:
######## TF-IDF Vectorizer #####################

from sklearn.feature_extraction.text import TfidfVectorizer

In [19]:
####### Models : SVM , NB , RF , ensemble ##############

In [21]:
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier

In [22]:
##### Creating PipeLine #####

from sklearn.pipeline import Pipeline

In [23]:
# SVC

In [25]:
SVC_Pipe = Pipeline([('TF', TfidfVectorizer()), ('SVC',LinearSVC(dual=True))])
SVC_Pipe.fit(X_train,Y_train)

Pipeline(steps=[('TF', TfidfVectorizer()), ('SVC', LinearSVC(dual=True))])

In [26]:
# NB

In [27]:
NB_Pipe = Pipeline([('TF', TfidfVectorizer()), ('NB', MultinomialNB())])
NB_Pipe.fit(X_train , Y_train)

Pipeline(steps=[('TF', TfidfVectorizer()), ('NB', MultinomialNB())])

In [28]:
# RF
RF_Pipe = Pipeline([('TF',TfidfVectorizer()),  ('RF',RandomForestClassifier(n_estimators=100))])
RF_Pipe.fit(X_train, Y_train)

Pipeline(steps=[('TF', TfidfVectorizer()), ('RF', RandomForestClassifier())])

In [29]:
###### Predict ######

In [30]:
SVC_predict = SVC_Pipe.predict(X_test)
NB_predict = NB_Pipe.predict(X_test)
RF_predict = RF_Pipe.predict(X_test)
predict_models = [SVC_predict, NB_predict, RF_predict]

In [35]:
#### Reports ####
from sklearn.metrics import confusion_matrix, classification_report

In [44]:
###  SVC : Predict ###
print(confusion_matrix(Y_test,SVC_predict))

[[1580    7]
 [  18  238]]


In [42]:
###  NB : Predict ###
print(confusion_matrix(Y_test,NB_predict))

[[1587    0]
 [  81  175]]


In [43]:
### RF: Predict ###
print(confusion_matrix(Y_test,RF_predict))

[[1587    0]
 [  47  209]]
